/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5n2QZFCqSfj
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

export function StreamPurchaseBody() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12 lg:py-16">
      <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
        <div className="grid gap-6">
          <div>
            <h1 className="text-3xl md:text-4xl font-bold">
              Acme Smart Vacuum
            </h1>
            <p className="text-muted-foreground text-lg">
              The ultimate cleaning companion for your home.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center gap-3">
              <DollarSignIcon className="w-6 h-6 text-primary" />
              <div>
                <h3 className="font-semibold text-2xl">$199.99</h3>
                <p className="text-muted-foreground">Free Shipping</p>
              </div>
            </div>
            <div>
              <h2 className="text-xl font-semibold">Key Features:</h2>
              <ul className="grid gap-2 mt-2">
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-primary" />
                  <span>Powerful suction for deep cleaning</span>
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-primary" />
                  <span>Smart navigation with obstacle avoidance</span>
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-primary" />
                  <span>Automatic dust bin emptying</span>
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-primary" />
                  <span>Voice control and app integration</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="grid gap-6">
          <div className="relative w-full max-w-2xl overflow-hidden rounded-lg aspect-video">
            <video className="w-full">
              <source
                src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
                type="video/mp4"
              />
            </video>
            <div className="absolute inset-x-0 bottom-0 grid gap-2 bg-gradient-to-b from-transparent to-black/50 p-4">
              <div className="flex items-center gap-3 text-white [&_svg]:text-white">
                <Button
                  size="icon"
                  variant="ghost"
                  className="w-9 h-9 hover:bg-black/50"
                >
                  <PlayIcon className="w-6 h-6 fill-white" />
                </Button>
                <Button
                  size="icon"
                  variant="ghost"
                  className="w-9 h-9 hover:bg-black/50"
                >
                  <Volume2Icon className="w-6 h-6 fill-white" />
                </Button>
                <div className="text-sm">1:20 / 3:45</div>
                <Button
                  size="icon"
                  variant="ghost"
                  className="ml-auto w-9 h-9 hover:bg-black/50"
                >
                  <MaximizeIcon className="w-6 h-6" />
                </Button>
              </div>
            </div>
          </div>
          <Button size="lg" className="w-full">
            Add to Cart
          </Button>
        </div>
      </div>
    </div>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}

function DollarSignIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  );
}

function MaximizeIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </svg>
  );
}

function PlayIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  );
}

function Volume2Icon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <path d="M15.54 8.46a5 5 0 0 1 0 7.07" />
      <path d="M19.07 4.93a10 10 0 0 1 0 14.14" />
    </svg>
  );
}
